/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.awt.Dimension;

/**
 *
 * @author Zile
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new formz Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        Dimension maxDimension = new Dimension(500, 500);
        this.setMaximumSize(maxDimension);

// Impede que o usuário redimensione a janela
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botao_rpg = new javax.swing.JToggleButton();
        botao_multplayer = new javax.swing.JToggleButton();
        botao_solo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(42, 42, 42));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione um modo de jogo");

        botao_rpg.setBackground(new java.awt.Color(0, 0, 0));
        botao_rpg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_rpg.setForeground(new java.awt.Color(255, 255, 255));
        botao_rpg.setSelected(true);
        botao_rpg.setText("RPG");
        botao_rpg.setBorderPainted(false);
        botao_rpg.setFocusPainted(false);
        botao_rpg.setFocusable(false);
        botao_rpg.setIconTextGap(10);
        botao_rpg.setRequestFocusEnabled(false);
        botao_rpg.setRolloverEnabled(false);
        botao_rpg.setVerifyInputWhenFocusTarget(false);

        botao_multplayer.setBackground(new java.awt.Color(0, 0, 0));
        botao_multplayer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_multplayer.setForeground(new java.awt.Color(255, 255, 255));
        botao_multplayer.setSelected(true);
        botao_multplayer.setText("2 Jogadores");
        botao_multplayer.setBorderPainted(false);
        botao_multplayer.setFocusPainted(false);
        botao_multplayer.setFocusable(false);
        botao_multplayer.setPreferredSize(new java.awt.Dimension(58, 27));
        botao_multplayer.setRequestFocusEnabled(false);
        botao_multplayer.setRolloverEnabled(false);
        botao_multplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_multplayerActionPerformed(evt);
            }
        });

        botao_solo.setBackground(new java.awt.Color(0, 0, 0));
        botao_solo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_solo.setForeground(new java.awt.Color(255, 255, 255));
        botao_solo.setSelected(true);
        botao_solo.setText("1 Jogador");
        botao_solo.setBorderPainted(false);
        botao_solo.setFocusPainted(false);
        botao_solo.setFocusable(false);
        botao_solo.setOpaque(false);
        botao_solo.setRequestFocusEnabled(false);
        botao_solo.setRolloverEnabled(false);
        botao_solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_soloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_solo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_multplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_rpg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(botao_rpg, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botao_multplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_solo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_multplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_multplayerActionPerformed
        // TODO add your handling code here:

        // fecha a janela atual
        this.dispose();

        // cria e exibe a janela "solo"
        Menu_Multplayer menuMultplayer = new Menu_Multplayer();
        menuMultplayer.setVisible(true);
    }//GEN-LAST:event_botao_multplayerActionPerformed

    private void botao_soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_soloActionPerformed
        // fecha a janela atual
        this.dispose();

        // cria e exibe a janela "solo"
        Menu_Solo menuSolo = new Menu_Solo();
        menuSolo.setVisible(true);
    }//GEN-LAST:event_botao_soloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botao_multplayer;
    private javax.swing.JToggleButton botao_rpg;
    private javax.swing.JToggleButton botao_solo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
